name: qassimha
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: any
  bloc_test: any
  blur: any
  dio: any
  #  google_fonts: any
  get: any
  carousel_slider: any
  cached_network_image: any
  shared_preferences: any
  animated_theme_switcher: any
  flutter_launcher_icons: any
  device_info_plus: any
  injectable: any
  intl: any
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  pretty_dio_logger: any
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.1.1
  device_preview: any
  skeletonizer: any
  firebase_analytics: any
  firebase_crashlytics: any
  cloud_firestore: any
  http:
  share_plus:
  auto_size_text: ^3.0.0
  url_launcher: any
  flutter_dotenv: any
  retrofit:
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.4
  another_flushbar: ^1.12.30
  animated_bottom_navigation_bar: ^1.4.0
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.6
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1
  equatable: ^2.0.5
  flutter_tts: ^4.2.3
  syncfusion_flutter_datepicker: ^29.2.10
  persistent_bottom_nav_bar: ^6.2.1
  just_audio: ^0.10.4
  showcaseview: ^4.0.1
  pdf: ^3.10.4
  isar_flutter_libs: ^4.0.0-dev.13
  google_fonts: any
  firebase_core: ^3.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.6.2
  json_serializable: ^6.6.1
  lints: ^5.0.0
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/Amiri-Regular.ttf

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
