name: qassimha
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.10.4
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  isar_flutter_libs: ^4.0.0-dev.13
  google_fonts: any

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Amiri-Regular.ttf

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
